IDIR=include
CC=i686-w64-mingw32-gcc
CXX=i686-w64-mingw32-g++
RC=wrc
INCLUDE_PATH=-I$(IDIR)
CFLAGS=$(INCLUDE_PATH) 

ODIR=src
LDIR=lib

LIBS=-lm -lpsapi -mwindows

CEXTRA       = -mno-clwb
CXXEXTRA     =
DEFINES      =
RCEXTRA      = 
RCFLAGS      = 

DLLS= odbc32 ole32 oleaut32 winspool odbccp32

_DEPS=h/lowlvl.h h/losu.h h/summoner.h
DEPS=$(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ=main.o low_functions.o search.o res/dlg_main.rc
OBJ=$(patsubst %,$(ODIR)/%,$(_OBJ))

_RES=res/dlg_main.rc
RES=$(patsubst %,$(ODIR)/%,$(_RES))

.SUFFIXES: .cpp .cxx .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<
	
.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

$(ODIR)/%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

floral_flyff_cheat.exe:  $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS) $(DLLS:%=-l%)
	

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o *~ core $(INCDIR)/*~ 
